begin;

alter table users
  add column if not exists employee_number text,
  add column if not exists user_name text,
  add column if not exists alternative_id text,
  add column if not exists biometric_id text,
  add column if not exists first_name text,
  add column if not exists middle_name text,
  add column if not exists last_name text,
  add column if not exists communication_email text,
  add column if not exists mobile_number_1 text,
  add column if not exists mobile_number_2 text,
  add column if not exists date_of_joining date,
  add column if not exists last_working_day date,
  add column if not exists gender_name text,
  add column if not exists leave_id text,
  add column if not exists attendance_id text,
  add column if not exists expense_id text,
  add column if not exists date_of_birth date,
  add column if not exists user_role_name text,
  add column if not exists worker_type text,
  add column if not exists user_profile text,
  add column if not exists is_differently_abled boolean,
  add column if not exists is_rejoinee boolean,
  add column if not exists prev_employee_number text,
  add column if not exists is_probation boolean,
  add column if not exists probation_date date,
  add column if not exists is_fixed_duration boolean,
  add column if not exists contract_start_date date,
  add column if not exists contract_end_date date,
  add column if not exists contract_extension_date date,
  add column if not exists contract_effective_date date,
  add column if not exists informal_start_date date,
  add column if not exists informal_end_date date,
  add column if not exists informal_effective_date date,
  add column if not exists type_id_0 text,
  add column if not exists type_id_1 text,
  add column if not exists type_id_12 text,
  add column if not exists payment_mode_name text,
  add column if not exists religion text,
  add column if not exists caste text,
  add column if not exists marital_status text,
  add column if not exists anniversary_date date,
  add column if not exists address_type text,
  add column if not exists address_line1 text,
  add column if not exists address_line2 text,
  add column if not exists country_name text,
  add column if not exists state_name text,
  add column if not exists district_name text,
  add column if not exists city_name text,
  add column if not exists pincode text,
  add column if not exists blood_group text,
  add column if not exists landline_no text,
  add column if not exists pan_no text,
  add column if not exists pan_holder text,
  add column if not exists uan_no text,
  add column if not exists license_no text,
  add column if not exists pf_no text,
  add column if not exists cibil_score text,
  add column if not exists cibil_score_date date,
  add column if not exists esi_no text,
  add column if not exists esi_dispensary text,
  add column if not exists is_pension_applicable boolean,
  add column if not exists is_international_worker boolean,
  add column if not exists is_inoperative boolean,
  add column if not exists worker_master_raw jsonb;

create table if not exists user_scope_org (
  id bigint generated always as identity primary key,
  origin_org_id bigint not null references organisations(id) on delete cascade,
  scope_org_id bigint not null references organisations(id) on delete cascade,
  user_id bigint not null references users(user_id) on delete cascade,
  employee_number text,
  user_name text,
  email text,
  ticket_role text not null,
  ticket_role_id bigint not null references roles(id) on delete restrict,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, scope_org_id)
);

create index if not exists user_scope_org_scope_idx
  on user_scope_org (scope_org_id, ticket_role_id, is_active);

commit;

